export enum __SCREENS {
  WELCOME_SCREEN = 'WELCOME_SCREEN',
  DRAWER_ONBOARDING_SCREEN = 'DRAWER_ONBOARDING_SCREEN',
  DRAWER_ONBOARDED_SCREEN = 'DRAWER_ONBOARDED_SCREEN',
  USERNAME = 'USERNAME',
  CREATE_IMPORT_WALLET = 'CREATE_IMPORT_WALLET',
  CREATE_PIN_CODE = 'CREATE_PIN_CODE',

  HOME_SCREEN = 'HOME',
}

export enum __NAVIGATORS {
  MAIN = 'MAIN',
  ONBOARDED = 'ONBOARDED',
  ONBOARDING = 'ONBOARDING',
}
