export enum __SCREENS {
  WELCOME_SCREEN = 'WELCOME_SCREEN',
  DRAWER_ONBOARDING_SCREEN = 'DRAWER_ONBOARDING_SCREEN',
  DRAWER_ONBOARDED_SCREEN = 'DRAWER_ONBOARDED_SCREEN',

  HOME_SCREEN = 'HOME',
}

export enum __NAVIGATORS {
  MAIN = 'MAIN',
  ONBOARDED = 'ONBOARDED',
  ONBOARDING = 'ONBOARDING',
}
